### ISSUE TITLE
Allow specifying sprites for click and hover events for a button

### ISSUE THREAD

**Issue by andrew-vos** [shdwcat/YUI#102]
I can specify a background sprite for a button like this:
```
  btn_main_menu:
    type: fragment
    content:
      type: button
      content: btn_main_menu
      background: ~spr_main_menu_button_default
      padding: 0
```

Would be good to be able to specify sprites for the generic hover and click events as well. Ideally this should not be specific to a mouse, but react to a keyboard/gamepad inputs as well (I can at least move focus with the keyboard right now with up/down keys)
